### PR TITLE
add chinese locale support

### PR DESCRIPTION
**Pull request by Suixinlei**
Hello, I have added chinese translation strings. And changed the option in header.html.

### CODE REVIEW

**Comment by demipixel** [comment]
Awesome work :) Is there any outpost name you'd like adding to Autotorio? ([Examples here](https://github.com/demipixel/autotorio/blob/master/assets/js/generators.js#L2))

**Comment by Suixinlei** [comment]
"Suixinlei" is Ok.
Your tool is very cool, but it visit slowly in China. Can I set a mirror version in China Server? It will be non-commercial.

**Comment by demipixel** [comment]
If you have a china server you can run it on, I could have something like cn.autotorio.com point to it (or some other domain name). How many ms does it take to load a page there?

**Comment by Suixinlei** [comment]
2000ms - 4000ms. Sometimes packet loss rate is very high.
I will host it in my aliyun server. It located in Zhejiang, China.

**Comment by Suixinlei** [comment]
ok, done. just set your cname like cn.autotorio.com to the domain name is ok.

http://autotorio.kouka.tech/

**Pull request merged**
