### PR TITLE
Adding French

### PR DESCRIPTION
**Pull request by OriginalsByToto**
Adding French strings in localisation.json and a selector option in header.html

Also removing a duplication object for "blueprint_tool" inside localisation.json

### CODE REVIEW

**Comment by demipixel** [comment]
Thank you so much! For your contribution, is there any blueprint name you'd like on Autotorio?

https://github.com/demipixel/autotorio/blob/master/assets/js/generators.js#L28

**Comment by OriginalsByToto** [comment]
A blueprint name ?

**Comment by demipixel** [comment]
You can make it so blueprint names when people export outposts would same some of the time "OriginalsByToto's Outpost" or something else, like "The Toto Outpost". Kinda like how Factorio names train stations and labs after early contributors. Just a little something to thank Autotorio's donators and contributors :)

**Comment by OriginalsByToto** [comment]
I don't know, I don't have any idea now, but if I make an other commit later (for something else), could I add it?

**Pull request merged**
