### PR TITLE
Localisation update

### PR DESCRIPTION
**Pull request by OriginalsByToto**
Working to localise entities names (not finished for all names in the blueprint replacer).
Adding English as default value for localised strings.

### CODE REVIEW

**Comment by OriginalsByToto** [comment]
Thank you!
I'm working to localise all the entities names.

**Comment by demipixel** [comment]
No, thank **you**! Incredible work, the site was long overdue for localisation in the nooks and crannies. Sorry about the delay merging, I've been sick for the past week.

**Comment by OriginalsByToto** [comment]
No problem, but do you want to keep english names for the entities in the blueprint replacer?

**Comment by demipixel** [comment]
What do you mean "keep English names"? I mean, I still plan on English being the primary language on the site, so hopefully the English localisation doesn't go anywhere :P

**Comment by OriginalsByToto** [comment]
Yes, of course, english is the primary language, but the game is translated in many languages and some of the translated names are not the same as english (at least in french).
I just talk about changing the entities names in the blueprint replacer with the chosen translation of the site.

**Pull request merged**
