### PR TITLE
this is the final edition of Chinese Translation from a noob

### PR DESCRIPTION
**Pull request by innocen3**
I am sure this is the complete correct edition for the translated script, but I don't have 100% confidence in assuring the correctness. so, please check the script and merge the script after checking, thank you.

### CODE REVIEW

**Comment by demipixel** [comment]
Hey, just FYI if you submit a pull request, you can still commit on the same branch and your changes will appear on the PR. I'll accept this when I get back!

**Comment by innocen3** [comment]
Okay, cool. by the way, the last Chinese guy hasn't built up the Chinese server for the mirror version of this website yet. So, like I do, we, a game group (like discord but we are using another software), would like to try to help my Chinese fellow to get easy to use this website. So, we are trying to build up a temporary experimental mirror server of this website. So far, the temporary experimental server will not face to the public, the user range is only limited in this game group as the server test.

**Comment by demipixel** [comment]
Alright, sounds good 👍 Want me to merge this or wait until you have more translations in?

**Comment by innocen3** [comment]
you can merge the branch now if you check the correctness.

**Comment by innocen3** [comment]
Please merge the branch asap.

**Pull request merged**
